import type { Rider } from './types';

export const TEAM_SIZE = 5;
export const BUDGET = 1150;

export const MOTOGP_RIDERS: Rider[] = [
    {
        id: 1,
        name: 'Marc Marquez',
        team: 'Ducati Lenovo Team',
        bike: 'Ducati',
        price: 600,
    },
    {
        id: 2,
        name: 'Jorge Martin',
        team: 'Aprilia Racing',
        bike: 'Aprilia',
        price: 260,
    },
    {
        id: 3,
        name: 'Pedro Acosta',
        team: 'Red Bull KTM Factory Racing',
        bike: 'KTM',
        price: 310,
    },
    {
        id: 4,
        name: 'Marco Bezzecchi',
        team: 'Aprilia Racing',
        bike: 'Aprilia',
        price: 390,
    },
    {
        id: 5,
        name: 'Luca Marini',
        team: 'Honda HRC Castrol',
        bike: 'Honda',
        price: 190,
    },
    {
        id: 6,
        name: 'Ai Ogura',
        team: 'Trackhouse MotoGP Team',
        bike: 'Aprilia',
        price: 170,
    },
    {
        id: 7,
        name: 'Franco Morbidelli',
        team: 'Pertamina Enduro VR46 MotoGP Team',
        bike: 'Ducati',
        price: 210,
    },
    {
        id: 8,
        name: 'Fabio Di giannantonio',
        team: 'Pertamina Enduro VR46 MotoGP Team',
        bike: 'Ducati',
        price: 200,
    },
    {
        id: 9,
        name: 'Brad Binder',
        team: 'Red Bull KTM Factory Racing',
        bike: 'KTM',
        price: 250,
    },
    {
        id: 10,
        name: 'Miguel Oliveira',
        team: 'Prima Pramac Yamaha',
        bike: 'Yamaha',
        price: 100,
    },
    {
        id: 11,
        name: 'Alex Rins',
        team: 'Monster Energy Yamaha MotoGP™',
        bike: 'Yamaha',
        price: 110,
    },
    {
        id: 12,
        name: 'Francesco Bagnaia',
        team: 'Ducati Lenovo Team',
        bike: 'Ducati',
        price: 320,
    },
    {
        id: 13,
        name: 'Pol Espargaró',
        team: 'Red Bull KTM Factory Racing',
        bike: 'KTM',
        price: 160,
    },
    {
        id: 14,
        name: 'Fabio Quartararo',
        team: 'Monster Energy Yamaha MotoGP™',
        bike: 'Yamaha',
        price: 190,
    },
    {
        id: 15,
        name: 'Fermin Aldeguer',
        team: 'Gresini Racing MotoGP™',
        bike: 'Ducati',
        price: 240,
    },
    {
        id: 16,
        name: 'Enea Bastianini',
        team: 'Red Bull KTM Tech 3',
        bike: 'KTM',
        price: 190,
    },
    {
        id: 17,
        name: 'Joan Mir',
        team: 'Honda HRC Castrol',
        bike: 'Honda',
        price: 110,
    },
    {
        id: 18,
        name: 'Alex Marquez',
        team: 'Gresini Racing MotoGP™',
        bike: 'Ducati',
        price: 290,
    },
    {
        id: 19,
        name: 'Jack Miller',
        team: 'Prima Pramac Yamaha',
        bike: 'Yamaha',
        price: 100,
    },
    {
        id: 20,
        name: 'Augusto Fernandez',
        team: 'Prima Pramac Yamaha',
        bike: 'Yamaha',
        price: 110,
        condition: 'Rider is unavailable',
    },
    {
        id: 21,
        name: 'Somkiat Chantra',
        team: 'LCR Honda',
        bike: 'Honda',
        price: 100,
        condition: 'Rider is injured',
    },
    {
        id: 22,
        name: 'Raul Fernandez',
        team: 'Trackhouse MotoGP Team',
        bike: 'Aprilia',
        price: 180,
    },
    {
        id: 23,
        name: 'Maverick Viñales',
        team: 'Red Bull KTM Tech 3',
        bike: 'KTM',
        price: 160,
        condition: 'Rider is injured',
    },
    {
        id: 24,
        name: 'Lorenzo Savadori',
        team: 'Aprilia Racing',
        bike: 'Aprilia',
        price: 100,
        condition: 'Rider is unavailable',
    },
    {
        id: 25,
        name: 'Johann Zarco',
        team: 'LCR Honda',
        bike: 'Honda',
        price: 110,
    },
    {
        id: 26,
        name: 'Taka Nakagami',
        team: 'Honda HRC Castrol',
        bike: 'Honda',
        price: 130,
        condition: 'Rider is unavailable',
    },
    {
        id: 27,
        name: 'Aleix Espargaró',
        team: 'Honda HRC Castrol',
        bike: 'Honda',
        price: 130,
        condition: 'Rider is unavailable',
    }
];
