
import type { Rider } from './types';

export const TEAM_SIZE = 5;
export const BUDGET = 11.0;

export const MOTOGP_RIDERS: Rider[] = [
    {
        id: 1,
        name: 'Marc Marquez',
        team: 'Ducati Lenovo Team',
        bike: 'Ducati',
        price: 6.0,
        priceChange: 200,
        condition: 'Rider on fire',
        totalPoints: 639,
        totalPodiums: 12,
        last3Races: [1, 1, 1],
    },
    {
        id: 2,
        name: 'Jorge Martin',
        team: 'Aprilia Racing',
        bike: 'Aprilia',
        price: 2.6,
        priceChange: 100,
        totalPoints: 61,
        totalPodiums: 0,
        last3Races: [7, '--', 4],
    },
    {
        id: 3,
        name: 'Pedro Acosta',
        team: 'Red Bull KTM Factory Racing',
        bike: 'KTM',
        price: 3.1,
        priceChange: 300,
        totalPoints: 298,
        totalPodiums: 2,
        last3Races: [3, 4, 2],
    },
    {
        id: 4,
        name: 'Marco Bezzecchi',
        team: 'Aprilia Racing',
        bike: 'Aprilia',
        price: 3.9,
        priceChange: 300,
        condition: 'Rider on fire',
        totalPoints: 363,
        totalPodiums: 5,
        last3Races: [2, 3, 3],
    },
    {
        id: 5,
        name: 'Luca Marini',
        team: 'Honda HRC Castrol',
        bike: 'Honda',
        price: 1.9,
        priceChange: 100,
        totalPoints: 178,
        totalPodiums: 0,
        last3Races: [12, 13, 5],
    },
    {
        id: 6,
        name: 'Ai Ogura',
        team: 'Trackhouse MotoGP Team',
        bike: 'Aprilia',
        price: 1.7,
        priceChange: 200,
        totalPoints: 181,
        totalPodiums: 0,
        last3Races: [14, 14, 11],
    },
    {
        id: 7,
        name: 'Franco Morbidelli',
        team: 'Pertamina Enduro VR46 MotoGP Team',
        bike: 'Ducati',
        price: 2.1,
        priceChange: 0,
        totalPoints: 281,
        totalPodiums: 2,
        last3Races: ['--', 11, 6],
    },
    {
        id: 8,
        name: 'Fabio Di giannantonio',
        team: 'Pertamina Enduro VR46 MotoGP Team',
        bike: 'Ducati',
        price: 2.0,
        priceChange: -100,
        totalPoints: 262,
        totalPodiums: 2,
        last3Races: [16, '--', 15],
    },
    {
        id: 9,
        name: 'Brad Binder',
        team: 'Red Bull KTM Factory Racing',
        bike: 'KTM',
        price: 2.5,
        priceChange: 200,
        totalPoints: 229,
        totalPodiums: 0,
        last3Races: [8, 7, 7],
    },
    {
        id: 10,
        name: 'Miguel Oliveira',
        team: 'Prima Pramac Yamaha',
        bike: 'Yamaha',
        price: 1.0,
        priceChange: 0,
        totalPoints: 46,
        totalPodiums: 0,
        last3Races: [17, 17, 12],
    },
    {
        id: 11,
        name: 'Alex Rins',
        team: 'Monster Energy Yamaha MotoGP™',
        bike: 'Yamaha',
        price: 1.1,
        priceChange: 0,
        totalPoints: 141,
        totalPodiums: 0,
        last3Races: [15, 16, 13],
    },
    {
        id: 12,
        name: 'Francesco Bagnaia',
        team: 'Ducati Lenovo Team',
        bike: 'Ducati',
        price: 3.2,
        priceChange: -300,
        totalPoints: 380,
        totalPodiums: 7,
        last3Races: [4, 8, 9],
    },
    {
        id: 13,
        name: 'Pol Espargaró',
        team: 'Red Bull KTM Factory Racing',
        bike: 'KTM',
        price: 1.6,
        priceChange: 0,
        totalPoints: 34,
        totalPodiums: 0,
        last3Races: [9, '--', 8],
    },
    {
        id: 14,
        name: 'Fabio Quartararo',
        team: 'Monster Energy Yamaha MotoGP™',
        bike: 'Yamaha',
        price: 1.9,
        priceChange: -100,
        totalPoints: 204,
        totalPodiums: 1,
        last3Races: [6, 15, 10],
    },
    {
        id: 15,
        name: 'Fermin Aldeguer',
        team: 'Gresini Racing MotoGP™',
        bike: 'Ducati',
        price: 2.4,
        priceChange: 0,
        totalPoints: 226,
        totalPodiums: 2,
        last3Races: [11, 2, 16],
    },
    {
        id: 16,
        name: 'Enea Bastianini',
        team: 'Red Bull KTM Tech 3',
        bike: 'KTM',
        price: 1.9,
        priceChange: -100,
        totalPoints: 207,
        totalPodiums: 0,
        last3Races: ['--', 5, '--'],
    },
    {
        id: 17,
        name: 'Joan Mir',
        team: 'Honda HRC Castrol',
        bike: 'Honda',
        price: 1.1,
        priceChange: 100,
        totalPoints: 107,
        totalPodiums: 0,
        last3Races: ['--', 6, '--'],
    },
    {
        id: 18,
        name: 'Alex Marquez',
        team: 'Gresini Racing MotoGP™',
        bike: 'Ducati',
        price: 2.9,
        priceChange: -300,
        condition: 'Rider on fire',
        totalPoints: 407,
        totalPodiums: 7,
        last3Races: ['--', 10, 14],
    },
    {
        id: 19,
        name: 'Jack Miller',
        team: 'Prima Pramac Yamaha',
        bike: 'Yamaha',
        price: 1.0,
        priceChange: 0,
        totalPoints: 102,
        totalPodiums: 0,
        last3Races: [10, 18, '--'],
    },
    {
        id: 20,
        name: 'Augusto Fernandez',
        team: 'Prima Pramac Yamaha',
        bike: 'Yamaha',
        price: 1.1,
        priceChange: 0,
        condition: 'Rider is unavailable',
        totalPoints: 44,
        totalPodiums: 0,
        last3Races: [18, '--', '--'],
    },
    {
        id: 21,
        name: 'Somkiat Chantra',
        team: 'LCR Honda',
        bike: 'Honda',
        price: 1.0,
        priceChange: 0,
        condition: 'Rider is injured',
        totalPoints: 65,
        totalPodiums: 0,
        last3Races: ['--', '--', '--'],
    },
    {
        id: 22,
        name: 'Raul Fernandez',
        team: 'Trackhouse MotoGP Team',
        bike: 'Aprilia',
        price: 1.8,
        priceChange: -300,
        totalPoints: 172,
        totalPodiums: 0,
        last3Races: [5, 9, '--'],
    },
    {
        id: 23,
        name: 'Maverick Viñales',
        team: 'Red Bull KTM Tech 3',
        bike: 'KTM',
        price: 1.6,
        priceChange: 0,
        condition: 'Rider is injured',
        totalPoints: 151,
        totalPodiums: 0,
        last3Races: ['--', '--', '--'],
    },
    {
        id: 24,
        name: 'Lorenzo Savadori',
        team: 'Aprilia Racing',
        bike: 'Aprilia',
        price: 1.0,
        priceChange: 0,
        condition: 'Rider is unavailable',
        totalPoints: 71,
        totalPodiums: 0,
        last3Races: ['--', '--', '--'],
    },
    {
        id: 25,
        name: 'Johann Zarco',
        team: 'LCR Honda',
        bike: 'Honda',
        price: 1.1,
        priceChange: -300,
        totalPoints: 203,
        totalPodiums: 2,
        last3Races: [13, 12, '--'],
    },
    {
        id: 26,
        name: 'Taka Nakagami',
        team: 'Honda HRC Castrol',
        bike: 'Honda',
        price: 1.3,
        priceChange: 0,
        condition: 'Rider is unavailable',
        totalPoints: 48,
        totalPodiums: 0,
        last3Races: ['--', '--', '--'],
    },
    {
        id: 27,
        name: 'Aleix Espargaró',
        team: 'Honda HRC Castrol',
        bike: 'Honda',
        price: 1.3,
        priceChange: 0,
        condition: 'Rider is unavailable',
        totalPoints: 14,
        totalPodiums: 0,
        last3Races: ['--', '--', '--'],
    }
];
